<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.springframework.samples</groupId>
    <artifactId>spring-petclinic-parent</artifactId>
    <version>3.2.0</version>
    <packaging>pom</packaging>
    <name>Spring PetClinic Multi-Module</name>

    <modules>
        <module>petclinic-core</module>
        <module>petclinic-services</module>
        <module>petclinic-web</module>
    </modules>
</project>
